on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: build-book

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      #
      RENV_CONFIG_REPOS_OVERRIDE: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup R
        id: install-r
        uses: r-lib/actions/setup-r@v1

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: '2.13'

      - name: Install TinyTeX
        uses: r-lib/actions/setup-tinytex@v1
        env:
          # install full prebuilt version
          TINYTEX_INSTALLER: TinyTeX

      - name: Cache packages
        uses: actions/cache@v2
        with:
          path: $HOME/.local/share/renv
          # This is both files that contains packages to install
          key: ${{ runner.os }}-r-renv-1-${{ hashFiles('index.Rmd', '18-references.Rmd') }}
          restore-keys: |
            ${{ runner.os }}-r-renv-1-
            ${{ runner.os }}-r-renv-
            ${{ runner.os }}-r-

      - name: Build site
        run: Rscript -e 'renv::activate(); bookdown::render_book("index.Rmd", quiet = FALSE)'
